project_id = "kygamyqwwzrpmxkxvzwt"

[functions.send-admin-email]
verify_jwt = false

[functions.receive-email]
verify_jwt = false

[functions.ai-email-reply]
verify_jwt = false

[functions.send-campaign]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.submit-order]
verify_jwt = false

[functions.process-abandoned-checkouts]
verify_jwt = false

[functions.outbound-call-handler]
verify_jwt = false